version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: fincore-redis
    command: redis-server --requirepass redis_fincore_2026 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - fincore-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_fincore_2026", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fincore-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fincore-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - fincore-zookeeper-data:/var/lib/zookeeper/data
      - fincore-zookeeper-log:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fincore-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fincore-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: fincore-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://fincore-kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "9092:9092"
    volumes:
      - fincore-kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - fincore-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fincore-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: FinCore
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: fincore-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: fincore-zookeeper:2181
    ports:
      - "8099:8080"
    networks:
      - fincore-network

volumes:
  fincore-redis-data:
    name: fincore-redis-data
  fincore-zookeeper-data:
    name: fincore-zookeeper-data
  fincore-zookeeper-log:
    name: fincore-zookeeper-log
  fincore-kafka-data:
    name: fincore-kafka-data

networks:
  fincore-network:
    name: fincore-network
    driver: bridge
