server.port=${SERVER_PORT:8081}
spring.application.name=audit-service

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/fincore_audit}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}
management.otlp.metrics.export.url=${OTLP_METRICS_URL:http://localhost:4318/v1/metrics}
management.otlp.tracing.endpoint=${OTLP_TRACING_URL:http://localhost:4318/v1/traces}

springdoc.api-docs.path=${OPENAPI_PATH:/v3/api-docs}
springdoc.swagger-ui.path=${SWAGGER_PATH:/swagger-ui.html}
