# ===================================================================
# Transfer Service — Saga orchestrator + WebSocket
# © 2026 Abel Gomez. Todos los derechos reservados.
# ===================================================================

spring.application.name=TRANSFER-SERVICE
server.port=8085
spring.threads.virtual.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fincore_transfers}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=transfer-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

grpc.client.account-service.address=static://${ACCOUNT_GRPC_HOST:localhost}:${ACCOUNT_GRPC_PORT:9083}
grpc.client.account-service.negotiation-type=plaintext
grpc.client.account-service.deadline=10000
grpc.client.fraud-service.address=static://${FRAUD_GRPC_HOST:localhost}:${FRAUD_GRPC_PORT:9086}
grpc.client.fraud-service.negotiation-type=plaintext
grpc.client.fraud-service.deadline=5000
grpc.client.ledger-service.address=static://${LEDGER_GRPC_HOST:localhost}:${LEDGER_GRPC_PORT:9084}
grpc.client.ledger-service.negotiation-type=plaintext
grpc.client.ledger-service.deadline=10000

resilience4j.circuitbreaker.instances.accountService.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=15s
resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=500ms

jwt.secret=${JWT_SECRET:fincore_jwt_hs512_secret_minimo_64_caracteres_2026_abel_gomez_banking}

saga.timeout.seconds=${SAGA_TIMEOUT:120}
saga.max.retries=${SAGA_MAX_RETRIES:3}

fraud.score.threshold.auto.approve=30
fraud.score.threshold.review=70
fraud.score.threshold.auto.reject=70

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.com.fincore.transfer=INFO

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
