server.port=8090
spring.application.name=fraud-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fincore_fraud
spring.datasource.username=fincore
spring.datasource.password=fincore123
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=fraud-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

grpc.port=9086
grpc.server.in-process-name=fraud-service

logging.level.com.fincore.fraud=DEBUG
logging.level.io.grpc=INFO

fraud.score.threshold.auto.approve=30
fraud.score.threshold.review=70
fraud.score.threshold.auto.reject=70
fraud.monto.multiplo.umbral=3.0
fraud.horario.inicio=0
fraud.horario.fin=5
fraud.dispositivo.ttl.dias=30
fraud.patron.monto.maximo=100.00
fraud.primer.transfer.grande.umbral=1000.00
fraud.velocity.max.transactions.per.hour=10
fraud.velocity.window.minutes=60
external.ip-api.url=http://ip-api.com/json

# Logging - save to service's logs directory
logging.file.path=logs

