# ===================================================================
# Eureka Server — Service Discovery
# © 2026 Abel Gomez. Todos los derechos reservados.
# ===================================================================

server.port=8761

spring.application.name=eureka-server

# Eureka Server Configuration
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# No necesitamos balanceador en el servidor de descubrimiento
eureka.server.enable-self-preservation=true
eureka.server.eviction-percentage-threshold=10
eureka.server.renewal-percent-threshold=0.85
eureka.server.renewal-interval-in-seconds=10
eureka.server.eviction-interval-timer-in-seconds=30

# Logging
logging.level.com.netflix.discovery=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO
logging.level.com.fincore.eurekaserver=INFO

# Management
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging - save to service's logs directory
logging.file.path=logs

