spring.application.name=${SPRING_APPLICATION_NAME:batch-service}
server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fincore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fincore_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fincore_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.batch.job.enabled=${SPRING_BATCH_JOB_ENABLED:true}
spring.batch.jdbc.initialize-schema=never
spring.batch.jstlter.type=${SPRING_BATCH_JSTLTER_TYPE:EMBEDDED}
spring.batch.datasource.url=${SPRING_BATCH_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fincore_batch}
spring.batch.datasource.username=${SPRING_BATCH_DATASOURCE_USERNAME:fincore_user}
spring.batch.datasource.password=${SPRING_BATCH_DATASOURCE_PASSWORD:fincore_password}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc.api-docs.path=${SPRING_DOC_API_DOCS_PATH:/v3/api-docs}
springdoc.swagger-ui.path=${SPRING_DOC_SWAGGER_UI_PATH:/swagger-ui.html}
